### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by hasindu2008** [harisankarsadasivan/DTWax#1]
Hi

Excited to try this out. Having a little issue with the compilation. Any tips?

```
nvcc -std=c++11 --ptxas-options=-v --default-stream per-thread  -O2 -lineinfo -gencode=arch=compute_86,code=sm_86 --compiler-options -Wall -DNO_REF_DEL -DFP16 -Xcompiler="-fopenmp -march=native" -O2 -lz -lhdf5 -I/usr/include/hdf5/serial -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lcudnn  main.cu -o main
nvcc fatal   : redefinition of argument 'optimize'
Makefile:14: recipe for target 'main' failed
make: *** [main] Error 1
```

PS: I am quite happy to see that the install_vbz.sh scripts from f5c is being useful. Always feel free to reuse them.

**Comment by harisankarsadasivan** [comment]
@hasindu2008.
Thanks for trying it out.
Yes, I really love that script. 
I see -O2 was specified twice. 
I have pushed a few clean-ups. Please pull and re-try now. 
Let me know how it goes!

**Comment by hasindu2008** [comment]
Seems like that -O2 is still coming up twice.
```
nvcc -std=c++11 --ptxas-options=-v --default-stream per-thread  -O2 -lineinfo -gencode=arch=compute_80,code=sm_80 --compiler-options -Wall -DNO_REF_DEL -DFP16 -Xcompiler="-fopenmp -march=native" -O2 -lz -lhdf5 -I/usr/include/hdf5/serial -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lcudnn  main.cu -o main
nvcc fatal   : redefinition of argument 'optimize'
Makefile:14: recipe for target 'main' failed
make: *** [main] Error 1
```
I manually tried removing -O2 and now `nvcc fatal   : Unsupported gpu architecture 'compute_80'`. The workstation I am trying to get it working is a Tesla V100 which is computed capability 7.0. Will DTWax work on pre-ampere architectures?

**Comment by harisankarsadasivan** [comment]
Thanks for your interest.
I believe "-gencode=arch=compute_70,code=sm_70" should work.
DTWax is tested only on *_80 and _*86 (high-performance Ampere chips, NVIDIA is at the next generation-Hopper now).
Please let me know if you face any further issues.
