### ISSUE TITLE
adaptive on the MK1C

### ISSUE THREAD

**Issue by husamia** [harisankarsadasivan/DTWax#2]
the adaptive is beta officially on the MK1C sequencer. Is it doable to run DTWax on the MK1C for enrichment of human genome?

**Comment by harisankarsadasivan** [comment]
MK1C is still a small platform to run compute-heavy basecalling.
I have not tested DTWax on MK1C. But looking at the spec [here](https://community.nanoporetech.com/requirements_documents/minion-mk1c-spec.pdf), theoretically, yes.
As long as you have CUDA, CUDNN and hdf5 installed, you could go ahead and recompile the software with the appropriate compute capability flags (*_70,*_80 etc.) in Makefile and reduce BLOCK_NUM and STREAM_NUM in [src](https://github.com/harisankarsadasivan/DTWax/tree/FAST5/src)/[include](https://github.com/harisankarsadasivan/DTWax/tree/FAST5/src/include)/common.hpp and run the binary. 
I know it used to be a Volta chip on the MK1C but I'm suspicious they changed it to Ampere sometime last year.
